# Generated by Django 3.2.3 on 2021-06-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(max_length=2)),
                ('Disease', models.TextField(max_length=100)),
                ('Prescribed_medicine', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=300)),
                ('Side_Effects', models.TextField(max_length=500)),
                ('Patient_Review', models.CharField(max_length=10)),
                ('Price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
