# Generated by Django 3.2.3 on 2021-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20210612_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_data',
            name='Feedback',
            field=models.CharField(blank='True', max_length=500),
        ),
    ]
