# Generated by Django 3.2.3 on 2021-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_medicine_data_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='health', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='health', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine_data',
            name='Feedback',
            field=models.TextField(blank='True', max_length=500),
        ),
    ]
