# Generated by Django 3.2.3 on 2021-06-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20210623_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
