# Generated by Django 3.2.3 on 2021-06-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20210624_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='display.medicine_data')),
            ],
        ),
    ]
